### ISSUE TITLE
Unicode characters, spaces and usage in URLs

### ISSUE THREAD

**Issue by Baggz** [apiaryio/abagnale#3]
Hello!

For the following blueprint (data structure)...

```
## Coupon Address (object)

- title: `home` (string)
```

...I'm getting the `Coupon Address.title-member` ID.

Just wondering—would it be possible to remove all spaces and `.toLowerCase()` so I can use the ID in URLs? Or is this something we'll do in a separate library/package/on the Apiary side?

One more thing...

```
## ŽŠČŘĎŤŇ (object)
```

...generates the `ŽŠČŘĎŤŇ.title-member` ID.

I think that in that case we should replace all unicode characters by ASCII (= `ZSCRDTN.title-member`).

What do you think, @danielgtaylor?

**Comment by danielgtaylor** [comment]
Whoops, this should be getting turned into a slug. Must have missed that!
